Yoga4Change Survey Data Collection System/Controllers/QuestionMgmtController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using Yoga4Change_Survey_Data_Collection_System.EntityFramework;
using Yoga4Change_Survey_Data_Collection_System.Models;
using Yoga4Change_Survey_Data_Collection_System.Models.Enums;
using Yoga4Change_Survey_Data_Collection_System.Models.ViewModel;
using Yoga4Change_Survey_Data_Collection_System.Repositories.Interfaces;

namespace Yoga4Change_Survey_Data_Collection_System.Controllers
{
   [Authorize(Roles = "Administrator, Survey Manager")]
    public class QuestionMgmtController : Controller
    {
        private readonly IQuestionRepository _questionRepository;
        private readonly IQuestionOptionRepository _questionOptionRepository;
        private readonly Y4CDbContext _dbContext;

        public QuestionMgmtController(IQuestionRepository questionRepository, IQuestionOptionRepository questionOptionRepository, Y4CDbContext dbContext)
        {
            _questionRepository = questionRepository;
            _questionOptionRepository = questionOptionRepository;
            _dbContext = dbContext;
        }

        [HttpGet]
        public ViewResult AddQuestion()
        {
            return View();
        }

        [HttpPost]
        public async Task<ViewResult> AddQuestionAsync(AddQuestionPostModel question)
        {
            var entity = await _questionRepository.AddQuestionAsync(question.ToQuestion());

            if (question.QuestionsOptions != null && (question.TypeId != QuestionType.Open_Ended || question.TypeId != QuestionType.Yes_No || question.TypeId != QuestionType.Date_Time))
            {
                var choices = new List<QuestionOption>();

                for (var i = 0; i < question.QuestionsOptions.Count; i++)
                {
                    var optionText = question.QuestionsOptions[i];
                    if (optionText != null)
                    {
                        var choice = new QuestionOption
                        {
                            QuestionId = entity.ID,
                            Content = optionText,
                            OrderInQuestion = i
                        };

                        choices.Add(choice);
                    }
                }
                _dbContext.QuestionsOptions.AddRange(choices);
                await _dbContext.SaveChangesAsync();
            }
            return View("SuccessAdd");
        }
        public async Task<ViewResult> QuestionBankAsync()
        {

            var questionList = await _questionRepository.GetQuestionListAsync();
            return View(questionList);
        }

        public async Task<ViewResult> DeleteQuestionAsync(int id)
        {
            await _questionRepository.DeleteQuestionAsync(id);

            return View("SuccessDelete");
        }

        [HttpGet]
        public async Task<ViewResult> UpdateQuestionAsync(int id)
        {
            var questionEdit = await _dbContext.Questions.Include(x => x.QuestionsOptions).FirstOrDefaultAsync(q => q.ID == id);

            return View(new UpdateQuestionModel(questionEdit));
        }

        [HttpPost]
        public async Task<ViewResult> UpdateQuestionAsync(UpdateQuestionModel question)
        {
            if (!ModelState.IsValid)
            {
                // TO DO - ERROR
                return View("QuestionBank");
            }

            var existingQuestion = await _dbContext.Questions.FirstOrDefaultAsync(q => q.ID == question.ID);

            // TO DO if existing question == null ----> error

            if (existingQuestion.TypeId == QuestionType.Checkbox || existingQuestion.TypeId == QuestionType.Dropdown || existingQuestion.TypeId == QuestionType.LikertScale || existingQuestion.TypeId == QuestionType.Radio_Button)
            {
                var existingChoices = await _dbContext.QuestionsOptions.Where(c => c.QuestionId == existingQuestion.ID).ToListAsync();

                _dbContext.QuestionsOptions.RemoveRange(existingChoices);
                await _dbContext.SaveChangesAsync();
            }

            existingQuestion.Content = question.Content;
            existingQuestion.Draft = question.Draft;
            existingQuestion.TypeId = question.TypeId;
            existingQuestion.LastModifiedAt = DateTime.UtcNow;


            _dbContext.Questions.Update(existingQuestion);
            await _dbContext.SaveChangesAsync();

            if (question.QuestionsOptions != null && (question.TypeId != QuestionType.Open_Ended || question.TypeId != QuestionType.Yes_No || question.TypeId != QuestionType.Date_Time))
            {
                var choices = new List<QuestionOption>();

                for (var i = 0; i < question.QuestionsOptions.Count; i++)
                {
                    var optionText = question.QuestionsOptions[i];
                    if (optionText != null)
                    {
                        var choice = new QuestionOption
                        {
                            QuestionId = existingQuestion.ID,
                            Content = optionText,
                            OrderInQuestion = i
                        };

                        choices.Add(choice);
                    }
                }
                _dbContext.QuestionsOptions.AddRange(choices);
                await _dbContext.SaveChangesAsync();
            }
            return View("SuccessUpdate");

        }

        public async Task<ViewResult> DuplicateQuestionAsync(int id)
        {
            var toCopy = await _dbContext.Questions.Include(x =>x.QuestionsOptions).FirstOrDefaultAsync(q => q.ID == id);
            var newQuestion = new Question

            {
                Content = toCopy.Content,
                TypeId = toCopy.TypeId,
                CreatedAt = DateTime.Now,
                LastModifiedAt = DateTime.Now
            };
            _dbContext.Questions.Add(newQuestion);
            await _dbContext.SaveChangesAsync();

            if (toCopy.QuestionsOptions != null && (toCopy.TypeId != QuestionType.Open_Ended || toCopy.TypeId != QuestionType.Yes_No || toCopy.TypeId != QuestionType.Date_Time))
            {
                var choices = new List<QuestionOption>();

                for (var i = 0; i < toCopy.QuestionsOptions.Count; i++)
                {
                    var optionText = toCopy.QuestionsOptions.Select(x => x.Content).ToList()[i];
                    if (optionText != null)
                    {
                        var choice = new QuestionOption
                        {
                            QuestionId = newQuestion.ID,
                            Content = optionText,
                            OrderInQuestion = i
                        };

                        choices.Add(choice);
                    }
                }
                _dbContext.QuestionsOptions.AddRange(choices);
        }
            await _dbContext.SaveChangesAsync();
            return View("SuccessAdd");

        }
    }
}

Yoga4Change Survey Data Collection System/Views/QuestionMgmt/AddQuestion.cshtml
@model Yoga4Change_Survey_Data_Collection_System.Models.ViewModel.AddQuestionPostModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var textOptionId = (int)Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType.Open_Ended;
}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add Question</title>

</head>
<body>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="AddQuestion" method="post" id="create-form" class="center">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Content" style="font-size: 18.72px; font-weight: bold">Content of the question: </label><br />
                    <textarea asp-for="Content" ID="Content" placeholder="Type you question here" rows="4" cols="40" runat="server"></textarea>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TypeId" class="control-label">Choose a question type:</label>
                    <select asp-for="TypeId" asp-items="Html.GetEnumSelectList<Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType>()" class="form-control" onchange="handleQuestionTypeChange();"></select>
                    <span asp-validation-for="TypeId" class="text-danger"></span>
                </div>
                <div id="question-options" style="display: none;">
                    <label asp-for="@Model.QuestionsOptions" class="control-label">Add a question choice: </label>
                    <button type="button" class="btn btn-primary btn-xs" id="btnAddChoice" onclick="addChoice()">+</button>
                </div><br />
                      <div id="checkbox" class="form-group">
                          <label class="control-label">Check if question not completed:</label><br />
                          <input asp-for="Draft" type="checkbox" />
                          <label asp-for="Draft"> Not completed - save as a draft</label><br>
                      </div>
                <div id="buttons" class="form-group">
                    <button type="button" class="btn btn-outline-info"> <a asp-controller="QuestionMgmt" asp-action="QuestionBank">Go Back</a></button>
                    <input type="button" value="Save Question" class="btn btn-outline-success" onclick="handleSubmit();" />
                </div>
            </form>
        </div>
    </div>
</body>
</html>

@section Scripts {
    <script type="text/javascript">
        var choiceCount = 0;
        var nextIndex = 0;
        var textId = @textOptionId;

        function addChoice() {
            choiceCount += 1;

            let formGroupId = `new-choice-${choiceCount}`;

            let formGroup = document.createElement("div");
            formGroup.className = "form-group question-options-parent";
            formGroup.id = formGroupId;

            let label = document.createElement("label");
            label.className = "control-label";
            label.innerText = `Choice`;

            let inputGroup = document.createElement("div");
            inputGroup.className = "input-group";

            let input = document.createElement("input");
            input.type = "text";
            input.className = "form-control choices";
            input.id = nextIndex;


            let inputGroupBtn = document.createElement("div");
            inputGroupBtn.className = "input-group-btn";

            let btnSubtract = document.createElement("button");
            btnSubtract.type = "button";
            btnSubtract.id = "btnRemoveChoice";
            btnSubtract.className = "btn btn-danger";
            btnSubtract.innerText = "-";
            btnSubtract.onclick = function () { removeChoice(formGroupId) };

            inputGroupBtn.appendChild(btnSubtract);
            inputGroup.appendChild(input);
            inputGroup.appendChild(inputGroupBtn);
            formGroup.appendChild(label);
            formGroup.appendChild(inputGroup);
            checkbox.before(formGroup);

            nextIndex++;
        }

        function removeChoice(formGroupId) {
            var formGroup = document.getElementById(formGroupId);
            formGroup.remove();
            choiceCount -= 1;
        }


        function handleQuestionTypeChange() {
            var selectList = get("#TypeId");
            var selectedValue = selectList.value;
            console.log(selectedValue);

            if (selectedValue == 1 || selectedValue == 2 || selectedValue == 3) {
                var options = document.querySelectorAll(".question-options-parent");
                for (var i = 0; i < options.length; i++) {
                    options[i].style.display = "none";
                }
                hide("question-options");
            }
            else {
                var options = document.querySelectorAll("question-options-parent");
                for (var i = 0; i < options.length; i++) {
                    options[i].style.display = "block";
                }
                show("question-options");
            }
        }
        

        function handleSubmit() {

            var inputs = document.getElementsByClassName('choices');

            for (var i = 0; i < inputs.length; i++) {
                inputs[i].name = `questionsOptions[${ i }]`;
            }

            var req = requiredContent();

            if (req == true) {
                document.getElementById('create-form').submit();
            }
        }

        function requiredContent() {
            var req = document.getElementById('Content');
            if (req == null || req.value == "") {
                alert('Please enter a question');
                return false;
            }
            else {
                return true;
            }
        }

        function get(selector) {
            if (!selector) {
                console.log("Element not found. No selector provided.");
                return;
            }

            let result = document.querySelector(selector);
            if (!result) {
                console.log(`Element not found: "${selector}"`);
                return;
            }

            return result;
        }

        function show(id) {
            var element = get(`#${id}`);

            if (element) {
                element.style.display = "block";
            }
        }

        function hide(id) {
            var element = get(`#${id}`);

            if (element) {
                element.style.display = "none";
            }
        }
    </script>
}

Yoga4Change Survey Data Collection System/Views/QuestionMgmt/QuestionBank.cshtml
@using Yoga4Change_Survey_Data_Collection_System.Models.Enums;

@model List<Yoga4Change_Survey_Data_Collection_System.Models.Question>
@{
    ViewBag.Title = "QuestionBank";
}
<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js" defer></script>


</head>

<body>
    <div><button type="button" class="btn btn-outline-info"> <a asp-controller="QuestionMgmt" asp-action="AddQuestion">Add Question</a></button><br /></div>

    <div>
        <table id="questionstable" class="table table-striped table-bordered dt-responsive" style="table-layout: auto;width: 100%;" cellspacing="0">
            <thead>
                <tr>
                    <th colspan="1" style="text-align : center"><label>Number</label></th>
                    <th colspan="1" style="text-align : center"><label asp-for="@Model.FirstOrDefault().Content"></label></th>
                    <th colspan="1" style="text-align : center"><label asp-for="@Model.FirstOrDefault().TypeId"></label></th>
                    <th colspan="1" style="text-align : center"><label asp-for="@Model.FirstOrDefault().CreatedAt"></label></th>
                    <th colspan="1" style="text-align : center"><label asp-for="@Model.FirstOrDefault().LastModifiedAt"></label></th>
                    <th colspan="1" style="text-align : center"><label asp-for="@Model.FirstOrDefault().Draft"></label></th>
                    <th colspan="1" style="text-align : center"><label>Edit</label></th>
                    <th colspan="1" style="text-align : center"><label>Duplicate</label></th>
                    <th colspan="1" style="text-align : center"><label>Delete</label></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var r in Model)
                {
                <tr>
                    <td style="text-align : center"></td>
                    <td>@r.Content</td>
                    <td>@r.TypeId.GetDisplayName()</td>
                    <td>@r.CreatedAt.ToString("MM/dd/yyyy")</td>
                    <td>@r.LastModifiedAt.ToString("MM/dd/yyyy")</td>
                    <td>@r.Draft.ToYesNoString()</td>
                    <td>@Html.ActionLink("Edit", "UpdateQuestion", new { id = r.ID }, new { @class = "btn btn-primary" })</td>
                    <td>@Html.ActionLink("Duplicate", "DuplicateQuestion", new { id = r.ID }, new { @class = "btn btn-success" })</td>
                    <td>@Html.ActionLink("Delete", "DeleteQuestion", new { id = r.ID }, new { @class = "btn btn-danger" })</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</body>

<script>

    $(document).ready(function () {

        $('#questionstable').DataTable();
    });

    var table = document.getElementsByTagName('table')[0],
        rows = table.getElementsByTagName('tr'), text = 'textContent' in document ?'textContent' : 'innerText';
    console.log(text);
    for (var i = 1, len = rows.length; i < len; i++) {
        rows[i].children[0][text] = i + rows[i].children[0][text];
    }
</script>

Yoga4Change Survey Data Collection System/Views/QuestionMgmt/SuccessAdd.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <h1 style="text-align:center"> Question was successfully added </h1>
    <p style="text-align:center"> Click <a asp-controller="QuestionMgmt" asp-action="QuestionBank"> here</a> to see added questions.</p>
    </body>
</html>

Yoga4Change Survey Data Collection System/Views/QuestionMgmt/SuccessDelete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <h1 style="text-align:center"> Question was successfully deleted </h1>
    <p style="text-align:center"> Click <a asp-controller="QuestionMgmt" asp-action="QuestionBank"> here</a> to see updated question bank.</p>
</body>
</html>

Yoga4Change Survey Data Collection System/Views/QuestionMgmt/SuccessUpdate.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <h1 style="text-align:center"> Question was successfully updated </h1>
    <p style="text-align:center"> Click <a asp-controller="QuestionMgmt" asp-action="QuestionBank"> here</a> to see added questions.</p>
    </body>
</html>

Yoga4Change Survey Data Collection System/Views/QuestionMgmt/UpdateQuestion.cshtml
@model Yoga4Change_Survey_Data_Collection_System.Models.ViewModel.UpdateQuestionModel
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
    var textOptionId = (int)Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType.Open_Ended;
}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Question</title>

</head>
<body>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="UpdateQuestion" method="post" id="edit-form" class="center">
                <input asp-for="ID" type="hidden" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Content" style="font-size: 18.72px; font-weight: bold">Content of the question: </label><br />
                    <textarea asp-for="Content" placeholder="Type you question here" rows="4" cols="40" required="required"></textarea>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TypeId" class="control-label">Choose a question type:</label>
                    <select asp-for="TypeId" asp-items="Html.GetEnumSelectList<Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType>()" class="form-control" onchange="handleQuestionTypeChange();"></select>
                    <span asp-validation-for="TypeId" class="text-danger"></span>
                </div>
                @{ var hidden = (Model.TypeId == Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType.Open_Ended || Model.TypeId == Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType.Yes_No || Model.TypeId == Yoga4Change_Survey_Data_Collection_System.Models.Enums.QuestionType.Date_Time); }

                @if (!hidden)
                {
                    <div id="question-options">
                        <label asp-for="@Model.QuestionsOptions" class="control-label"></label>
                        <button type="button" class="btn btn-primary btn-xs" id="btnAddChoice" onclick="addChoice()">+</button>

                        @for (int i = 0; i < Model.QuestionsOptions.Count; i++)
                        {
                            var parentId = $"existing-choice-{i}";

                            <div class="form-group question-option-parent" id="@parentId">
                                <label asp-for="@Model.QuestionsOptions[i]" class="control-label">Choice</label>
                                <div class="input-group">
                                    <input asp-for="@Model.QuestionsOptions[i]" type="text" class="choices form-control" />
                                    <div class="input-group-btn">
                                        <button type="button" id="btnRemoveChoice" class="btn btn-danger" onclick="removeChoice('@parentId')">-</button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <div id="question-options" style="display: none;">
                        <label asp-for="@Model.QuestionsOptions" class="control-label"></label>
                        <button type="button" class="btn btn-primary btn-xs" id="btnAddChoice" onclick="addChoice()">+</button>
                    </div>
                }
                <div id="checkbox" class="form-group">
                    <label class="control-label">Check if question not completed:</label><br />
                    <input asp-for="Draft" type="checkbox" />
                    <label asp-for="Draft"> Not completed - save as a draft</label><br>
                </div>
                <div id="buttons" class="form-group">
                    <button type="button" class="btn btn-outline-info"> <a asp-controller="QuestionMgmt" asp-action="QuestionBank">Go Back</a></button>
                    <input type="button" value="Save Question" class="btn btn-outline-success" onclick="handleSubmit();" />
                </div>
            </form>
        </div>
    </div>
</body>
</html>

@section Scripts {
    <script type="text/javascript">
        var choiceCount = 0;
        var nextIndex = 0;
        var textId = @textOptionId;

        function addChoice() {
            choiceCount += 1;

            let formGroupId = `new-choice-${choiceCount}`;

            let formGroup = document.createElement("div");
            formGroup.className = "form-group question-options-parent";
            formGroup.id = formGroupId;

            let label = document.createElement("label");
            label.className = "control-label";
            label.innerText = `Choice`;

            let inputGroup = document.createElement("div");
            inputGroup.className = "input-group";

            let input = document.createElement("input");
            input.type = "text";
            input.className = "form-control choices";
            input.id = nextIndex;


            let inputGroupBtn = document.createElement("div");
            inputGroupBtn.className = "input-group-btn";

            let btnSubtract = document.createElement("button");
            btnSubtract.type = "button";
            btnSubtract.id = "btnRemoveChoice";
            btnSubtract.className = "btn btn-danger";
            btnSubtract.innerText = "-";
            btnSubtract.onclick = function () { removeChoice(formGroupId) };

            inputGroupBtn.appendChild(btnSubtract);
            inputGroup.appendChild(input);
            inputGroup.appendChild(inputGroupBtn);
            formGroup.appendChild(label);
            formGroup.appendChild(inputGroup);
            checkbox.before(formGroup);

            nextIndex++;
        }

        function removeChoice(formGroupId) {
            var formGroup = document.getElementById(formGroupId);
            formGroup.remove();
            choiceCount -= 1;
        }


        function handleQuestionTypeChange() {
            var selectList = get("#TypeId");
            var selectedValue = selectList.value;
            console.log(selectedValue);

            if (selectedValue == 1 || selectedValue == 2 || selectedValue == 3) {
                var options = document.querySelectorAll(".question-options-parent");
                for (var i = 0; i < options.length; i++) {
                    options[i].style.display = "none";
                }
                hide("question-options");
            }
            else {
                var options = document.querySelectorAll(".question-options-parent");
                for (var i = 0; i < options.length; i++) {
                    options[i].style.display = "block";
                }
                show("question-options");
            }
        }

        function handleSubmit() {
            var inputs = document.getElementsByClassName('choices');

            for (var i = 0; i < inputs.length; i++) {
                inputs[i].name = `questionsOptions[${ i }]`;
            }
            var req = required();

            if (req == true) {
                document.getElementById('edit-form').submit();
            }
        }

        function required() {
            var req = document.getElementById('Content');
            if (req == null || req.value == "") {
                alert('Please enter a question');
                return false;
            }
            else {
                return true;
            }
        }

        function get(selector) {
            if (!selector) {
                console.log("Element not found. No selector provided.");
                return;
            }

            let result = document.querySelector(selector);
            if (!result) {
                console.log(`Element not found: "${selector}"`);
                return;
            }

            return result;
        }

        function show(id) {
            var element = get(`#${id}`);

            if (element) {
                element.style.display = "block";
            }
        }

        function hide(id) {
            var element = get(`#${id}`);

            if (element) {
                element.style.display = "none";
            }
        }

    </script>
}