Yoga4Change Survey Data Collection System/Controllers/ResponsesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Yoga4Change_Survey_Data_Collection_System.Repositories.Interfaces;

namespace Yoga4Change_Survey_Data_Collection_System.Controllers
{
   [Authorize(Roles = "Administrator, Survey Manager, Researcher")]
    public class ResponsesController : Controller
    {
        private readonly IResponseRepository _responseRepository;
        public ResponsesController(IResponseRepository responseRepository)
        {
            _responseRepository = responseRepository;
        }
        [Authorize]
        public ViewResult Dashboard()
        {
            return View();
        }
        [Authorize]
        public async Task<ViewResult> CompleteSurveys()
        {
            var responseList = await _responseRepository.GetResponseListAsync();
            return View(responseList);
            
        }

    }
}

Yoga4Change Survey Data Collection System/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Yoga4Change_Survey_Data_Collection_System.Areas.Identity.Data;
using Yoga4Change_Survey_Data_Collection_System.Models;

namespace Yoga4Change_Survey_Data_Collection_System.Controllers
{
   [Authorize(Roles = "Administrator")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;
        UserManager<Y4CUser> userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<Y4CUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }
        public IActionResult Create()
        {
            return View(new IdentityRole());
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        // Role ID is passed from the URL to the action
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            // Find the role by Role ID
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            // Retrieve all the Users
            foreach (var user in userManager.Users.ToList())
            {
                // If the user is in this role, add the username to
                // Users property of EditRoleViewModel. This model
                // object is then passed to the view for display
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        // This action responds to HttpPost and receives EditRoleViewModel
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                // Update the Role using UpdateAsync
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();
            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    FullName = user.FullName,
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

Yoga4Change Survey Data Collection System/Controllers/SurveyMgmtController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Yoga4Change_Survey_Data_Collection_System.EntityFramework;
using Yoga4Change_Survey_Data_Collection_System.Models;
using Yoga4Change_Survey_Data_Collection_System.Repositories.Interfaces;
using Yoga4Change_Survey_Data_Collection_System.Models.ViewModel;
using System.Dynamic;

namespace Yoga4Change_Survey_Data_Collection_System.Controllers
{
   [Authorize(Roles = "Administrator, Survey Manager, Researcher")]
    public class SurveyMgmtController : Controller
    {
        private readonly ISurveyRepository _surveyRepository;
        private readonly IQuestionRepository _questionRepository;
        private readonly Y4CDbContext _dbContext;

        public SurveyMgmtController(ISurveyRepository surveyRepository, IQuestionRepository questionRepository, Y4CDbContext dbContext)
        {
            _surveyRepository = surveyRepository;
            _questionRepository = questionRepository;
            _dbContext = dbContext;
        }

        public ViewResult CreateSurvey()
        {
            return View();
        }

        public async Task<ViewResult> CreateAsync()
        {
            //get reference to question list to display questions to add to a survey
            var questionList = await _questionRepository.GetQuestionListAsync();
            //var surveyList = await _surveyRepository.GetSurveyListAsync(); the reference to the survey repo may not be necessary for this action method
            AddSurveyViewModel viewModel = new AddSurveyViewModel();
            viewModel.Questions = questionList;
            //viewModel.Survey = surveyList;
            return View(viewModel);
        }

        public async Task<ViewResult> AddSurveyAsync(Survey survey)
        {
            //await _surveyRepository.AddSurveyAsync(survey);
            return View("SuccessAdd");
        }

        public async Task<ViewResult> SurveyListAsync()
        {
            //var surveyList = await _surveyRepository.GetSurveyListAsync();
            return View(/*surveyList*/);
        }

        public async Task<ViewResult> EditSurveyAsync(int id)
        {
            //var surveyEdit = await _dbContext.Surveys.FirstOrDefaultAsync(s => s.ID == id);
            return View(/*surveyEdit*/);
        }

        public async Task<ViewResult> DeleteSurveyAsync(int id)
        {
            await _surveyRepository.DeleteSurveyAsync(id);
            return View("SuccessDelete");
        }

        [HttpGet]
        public ViewResult Surveys()
        {
            return View();
        }
    }
}

Yoga4Change Survey Data Collection System/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Yoga4Change_Survey_Data_Collection_System.Areas.Identity.Data;
using Yoga4Change_Survey_Data_Collection_System.Models;
using Yoga4Change_Survey_Data_Collection_System.Repositories.Interfaces;

namespace Yoga4Change_Survey_Data_Collection_System.Controllers
{
  [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        UserManager<Y4CUser> userManager;
        RoleManager<IdentityRole> roleManager;
        private readonly IUserRepository _userRepository; 
        public UserController(UserManager<Y4CUser> userManager, IUserRepository _userRepository)
        {
            this._userRepository = _userRepository;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            var users = userManager.Users.ToList();
            return View(users);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string Id)
        {
            var user = await userManager.FindByIdAsync(Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("Index");
            }
        }
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }

            // GetClaimsAsync retunrs the list of user Claims
            var userClaims = await userManager.GetClaimsAsync(user);
            // GetRolesAsync returns the list of user Roles
            var userRoles = await userManager.GetRolesAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                FullName = user.FullName,
                Email = user.Email,
                UserName = user.UserName,
                Claims = userClaims.Select(c => c.Value).ToList(),
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                user.FullName = model.FullName;
                user.Email = model.Email;
                //user.UserName = model.UserName;
                

                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }
    }

}

Yoga4Change Survey Data Collection System/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Yoga4Change_Survey_Data_Collection_System.Areas.Identity.Data

@inject SignInManager<Y4CUser> SignInManager
@inject UserManager<Y4CUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Yoga4Change Survey Data Collection System</title>
    <link rel="icon" href="~/lib/Images/y4c-logo2.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="style.css" rel="stylesheet" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type='text/javascript' src='loadImg.js'></script>
</head>
<body>
    <div class="se-pre-con"></div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="navbar-header pull-left">
                <a class="navbar-brand" href="@Url.Action("Dashboard", "Responses")">
                    <div style="width: 150px; height: 150px;">
                        <img src="/lib/Images/y4c-logo.png" alt="Site Logo" style="height:100%; width:100%; object-fit: contain" />
                    </div>
                </a>
            </div>
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="align-content:baseline">
                    <ul class="navbar-nav nav-tabs flex-grow-1">
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator") || User.IsInRole("Survey Manager"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SurveyMgmt" asp-action="Create">Create Survey</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="QuestionMgmt" asp-action="QuestionBank">Question Bank</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SurveyMgmt" asp-action="Surveys">Surveys</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator") || User.IsInRole("Survey Manager") || User.IsInRole("Researcher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Responses" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Responses" asp-action="CompleteSurveys">Completed Surveys</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
                        {
                            <li class="nav-item dropdown">
                                <a class=" text-dark nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administrator</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
                <div class="col-md-3">
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Yoga4Change Survey Data Collection System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>